---
# Copyright (C) 2020 Roman Danko
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (CentOS 8) Install EPEL & ELRepo repository
  ansible.builtin.yum:
    name:
      - yum-utils
      - epel-release
      - elrepo-release
    update_cache: true
    state: present

- name: (CentOS 8) Install WireGuard packages
  ansible.builtin.yum:
    name:
      - "kmod-wireguard"
      - "wireguard-tools"
    state: present
